# Generated by Django 3.2.25 on 2025-07-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_connection', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='titl',
            new_name='title',
        ),
    ]
