# Generated by Django 3.2.25 on 2025-09-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_connection', '0005_auto_20250830_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
