# Generated by Django 3.2.25 on 2025-09-04 16:03

import db_connection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connection', '0006_rename_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=db_connection.models.recipe_image_file_path),
        ),
    ]
